<a href="https://colab.research.google.com/github/talhabhati/Anomaly-detection-using-pytorch/blob/main/tensor_in_pytorch_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
torch.__version__

'2.9.0+cpu'

In [3]:
#tensor data types
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [4]:
#tensor data types
torch.tensor([1.0,2.0,3.0], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [6]:
#mathematical operations on tensors
x=torch.rand(2,2)
x

tensor([[0.4621, 0.8673],
        [0.7174, 0.3868]])

In [7]:
#addition
x+2

tensor([[2.4621, 2.8673],
        [2.7174, 2.3868]])

In [8]:
#subtraction
x-2

tensor([[-1.5379, -1.1327],
        [-1.2826, -1.6132]])

In [9]:
#multiplication
x*2

tensor([[0.9241, 1.7345],
        [1.4348, 0.7737]])

In [10]:
#division
x/2

tensor([[0.2310, 0.4336],
        [0.3587, 0.1934]])

In [11]:
#power
x**2

tensor([[0.2135, 0.7521],
        [0.5147, 0.1496]])

In [13]:
a=torch.rand(2,3)
b=torch.rand(2,3)
print(a)
print(b)

tensor([[0.9933, 0.2895, 0.3875],
        [0.3865, 0.7293, 0.1066]])
tensor([[0.7021, 0.1417, 0.9238],
        [0.6381, 0.9843, 0.8811]])


In [14]:
#addition
a+b

tensor([[1.6955, 0.4311, 1.3113],
        [1.0247, 1.7136, 0.9877]])

In [ ]:
#- ,/, *, power are same

In [16]:
c=torch.tensor([-1,-2,3,-4])
c

tensor([-1, -2,  3, -4])

In [17]:
#to get absolute value
torch.abs(c)

tensor([1, 2, 3, 4])

In [18]:
#to get negative value
torch.neg(c)

tensor([ 1,  2, -3,  4])

In [19]:
#to get round off value
d=torch.tensor([2.31,1.32,4.01])
torch.round(d)

tensor([2., 1., 4.])

In [20]:
#ceil oper wala number pe la jata ah
torch.ceil(d)

tensor([3., 2., 5.])

In [21]:
#floor pichla number pe la jata ha
torch.floor(d)

tensor([2., 1., 4.])

In [23]:
#clamp aik range ma la ata ha numbers ko
torch.clamp(d,min=2, max=4)

tensor([2.3100, 2.0000, 4.0000])

In [32]:
e=torch.randint(size=(2,3),low=2,high=10 ,dtype=torch.float32)
print(e)

tensor([[4., 7., 3.],
        [8., 4., 7.]])


In [28]:
#all numbers are added
torch.sum(e)

tensor(33)

In [29]:
#to add rows
torch.sum(e,dim=0)

tensor([ 9,  9, 15])

In [30]:
#to add columns
torch.sum(e,dim=1)

tensor([13, 20])

In [37]:

torch.mean(e)


tensor(5.5000)

In [36]:
torch.std(e)

tensor(2.0736)

In [35]:
torch.median(e)


tensor(4.)

In [38]:
torch.var(e)


tensor(4.3000)

In [39]:
torch.argmax(e)


tensor(3)

In [40]:
torch.argmin(e)

tensor(2)

In [45]:
#matrix operation
g=torch.randint(size=(2,2),low=0,high=10)
h=torch.randint(size=(2,2),low=0,high=10)
print(g)
print(h)

tensor([[8, 1],
        [3, 9]])
tensor([[2, 9],
        [2, 5]])


In [46]:
#matrix multiplication
torch.matmul(g,h)

tensor([[18, 77],
        [24, 72]])

In [48]:
#to get dot product
vec1=torch.tensor([1,2,3])
vec2=torch.tensor([4,5,6])
torch.dot(vec1,vec2)

tensor(32)

In [53]:
#to transpose number
torch.transpose(g,0,1)

tensor([[8, 3],
        [1, 9]])