<a href="https://colab.research.google.com/github/talhabhati/Anomaly-detection-using-pytorch/blob/main/tensors_shape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Tensors shape
import torch
print(torch.__version__)

2.9.0+cpu


In [ ]:
x=torch.tensor([[1,2,3],[7,8,9]])
x

tensor([[1, 2, 3],
        [7, 8, 9]])

In [ ]:
#to check shape of tensor
x.shape

torch.Size([2, 3])

In [ ]:
#to copy shape like a tensor
torch.empty_like(x)

tensor([[3180222411935070754, 4189017755886035488, 7308535291872901920],
        [4189017755886051700, 8027140907415206688, 7018332503360695925]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x)

NotImplementedError: "check_uniform_bounds" not implemented for 'Long'