<a href="https://colab.research.google.com/github/talhabhati/Anomaly-detection-using-pytorch/blob/main/tensor_on_GPU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
torch.__version__

'2.9.0+cu128'

In [5]:
torch.cuda.is_available()

True

In [6]:
device=torch.device('cuda')

In [9]:
torch.rand((2,3), device=device)

tensor([[0.6879, 0.4939, 0.7181],
        [0.3671, 0.4263, 0.7040]], device='cuda:0')

In [ ]:
#move existing tensor on GPU
c=a.to(device)

In [10]:
#reshapping tensors
e=torch.eye(4,4)
e

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [11]:
#reshapping
e.reshape(2,2,2,2)


tensor([[[[1., 0.],
          [0., 0.]],

         [[0., 1.],
          [0., 0.]]],


        [[[0., 0.],
          [1., 0.]],

         [[0., 0.],
          [0., 1.]]]])

In [12]:
#flatten
e.flatten()

tensor([1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.])

In [16]:
#
r=torch.rand(2,3,4)
r

tensor([[[0.1342, 0.7313, 0.3481, 0.1406],
         [0.5542, 0.5875, 0.0103, 0.8428],
         [0.6183, 0.1281, 0.8603, 0.0469]],

        [[0.2389, 0.5511, 0.7665, 0.0860],
         [0.9554, 0.2898, 0.6348, 0.9606],
         [0.5368, 0.6158, 0.4882, 0.9031]]])

In [15]:
r.permute(1,0,2)

tensor([[[0.2030, 0.5342, 0.6036, 0.9111],
         [0.9834, 0.2385, 0.2503, 0.9138]],

        [[0.6319, 0.2443, 0.9381, 0.6230],
         [0.0059, 0.4396, 0.7312, 0.8718]],

        [[0.8376, 0.2932, 0.6507, 0.4962],
         [0.9866, 0.9904, 0.7355, 0.5363]]])

In [18]:
f=torch.rand(226,226,3)
f.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [19]:
u=torch.rand(1,20)
u.squeeze(0).shape

torch.Size([20])

In [27]:
#pytorch and numpy
import numpy as np
a=torch.tensor([1,2,3])
a
#convert tensor to aumpy array
b=a.numpy()
b

array([1, 2, 3])

In [31]:
t=np.array([1,2,3,4])
t

array([1, 2, 3, 4])

In [34]:
#convert array to tensor
g=torch.from_numpy(t)
g

tensor([1, 2, 3, 4])