In [1]:
import torch
#to check version of pytorch
print(torch.__version__)

2.9.0+cpu


In [2]:
import torch

if torch.cuda.is_available():
    print("✅ GPU is available")
    print("GPU name:", torch.cuda.get_device_name(0))
else:
    print("❌ GPU is NOT available")

#if you want to get GPU then go to runtime and change runtime type


❌ GPU is NOT available


In [4]:
#empty
er=torch.empty(2,3)
print(er)

tensor([[-1.5180e+06,  4.3272e-41,  2.1447e-21],
        [ 0.0000e+00,  1.6405e-38,  0.0000e+00]])


In [7]:
#check type
type(er)
#print(type(er))

torch.Tensor

In [8]:
#using zeros. we get tensor of where all values are zero
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
#using rand. we get values between 0 to 1 randomly
torch.rand(2,3)

tensor([[0.8514, 0.3525, 0.6068],
        [0.2073, 0.1310, 0.8846]])

In [14]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [15]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [16]:
#using tensor
torch.tensor([[1,2,3],[5,6,7]])

tensor([[1, 2, 3],
        [5, 6, 7]])

In [17]:
#using arange
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [24]:
#using linspace
torch.linspace(0,10,7)

tensor([ 0.0000,  1.6667,  3.3333,  5.0000,  6.6667,  8.3333, 10.0000])

In [25]:
#using eye , we make identity matrix
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [26]:
#using full
torch.full((3,3),4)

tensor([[4, 4, 4],
        [4, 4, 4],
        [4, 4, 4]])